# Generated by Django 5.2.4 on 2025-07-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usermanagement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="authacc",
            name="verified",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user has verified their email address.",
            ),
        ),
    ]
